// Code generated by github.com/tv42/becky -- DO NOT EDIT.

package static

var _ = addAsset(asset{Name: "notes.css", Content: "" +
	"p {\n  margin: 10px;\n}\n\n#presenter-slides {\n  display: block;\n  margin-top: -10px;\n  margin-left: -17px;\n  position: fixed;\n  border: 0;\n  width : 146%;\n  height: 750px;\n\n  transform: scale(0.7, 0.7);\n  transform-origin: top left;\n  -moz-transform: scale(0.7);\n  -moz-transform-origin: top left;\n  -o-transform: scale(0.7);\n  -o-transform-origin: top left;\n  -webkit-transform: scale(0.7);\n  -webkit-transform-origin: top left;\n}\n\n#presenter-notes {\n  margin-top: -180px;\n  font-family: 'Open Sans', Arial, sans-serif;\n  height: 30%;\n  width: 100%;\n  overflow: scroll;\n  position: fixed;\n  top: 706px;\n}\n" +
	"", etag: `"S+RBEBurC48="`})
